scripts/database-delete.sh, scripts/database-setup.sh, scripts/variables.sh
Creating bash scripts for setting up postgreSQL database locally.
=> Bash scripts for database setup

server/middlewares/token.js
Getting the token from the request headers and using it for validation.
=> Token validation middleware

src/assets/css/main.sass, src/assets/css/ui/post.sass, src/assets/images/icons/arrow.vue, src/components/layout/Post.vue
Showing number of upvotes, title, bodyMarkdown.
| design |
| -- |
| ![Screenshot_2020-02-05_at_25644_PM](https://user-images.githubusercontent.com/29014463/73830313-7c551b00-482a-11ea-952d-65dede8e46ea.jpg) |
=> Post component

src/components/layout/Auth.vue
Storing member login data to localStorage _(member_id and token)_.
=> Login axios call

src/components/layout/LatestPosts.vue
| view |
| --- |
| ![Screen Recording 2020-02-06 at 1 16 39 PM](https://user-images.githubusercontent.com/29014463/73916266-22fcf280-48e3-11ea-9446-51a32d034fec.gif) |
=> Show latests posts

package.json, scripts/database-setup.sh, server/controllers/post/create.js, server/controllers/post/getPostById.js, server/controllers/post/updatePostById.js, yarn.lock
Using `nanoid@2.1.11` package to generate unique ID for each post.
This package fulfil the needs in a sense the generated ID is not too short or long.
=> Replace slugID with postID

server/database/index.js
Create database schema using Knex.
=> Database schema

src/assets/css/ui/pages/post/view.sass, src/components/layout/CreatePost.vue, src/components/layout/Header.vue, src/components/layout/LatestPosts.vue, src/components/layout/OldestPosts.vue, src/pages/Join.vue, src/pages/Login.vue, src/pages/post/Edit.vue, src/pages/post/View.vue, src/pages/user/Settings.vue, src/store/modules/user.js
=> Update APIs routes in Frontend

package.json, server/controllers/post/filterPost.js, src/assets/css/components/loading.sass, src/assets/css/main.sass, src/assets/images/icons/loading.vue, src/components/layout/LatestPosts.vue, src/components/layout/OldestPosts.vue, src/components/ui/Loading.vue, src/main.js, yarn.lock
Add pagination to posts API and frontend using 'vue-infinite-loading' package.
=> Pagination

frontend/src/components/Navbar.vue, frontend/src/pages/board/Boards.vue, frontend/src/routes.js, frontend/src/styles/main.sass, frontend/src/styles/pages/board/boards.sass, frontend/src/styles/pages/dashboard/overview.sass, frontend/src/styles/variables.sass
=> Create boards page

frontend/src/pages/board/Boards.vue, frontend/src/pages/dashboard/Overview.vue, server/controllers/boards/filter.js
=> Add posts count to boards list

frontend/src/components/post/CreatePost.vue, frontend/src/components/post/LatestPosts.vue, frontend/src/components/post/OldestPosts.vue, frontend/src/components/post/Post.vue, frontend/src/pages/Homepage.vue, frontend/src/pages/board/Board.vue, frontend/src/pages/board/Boards.vue, frontend/src/routes.js, server/controllers/boards/boardBySlug.js, server/controllers/boards/boardPosts.js, server/controllers/boards/index.js, server/controllers/post/create.js, server/database/migrations/20200913090914_boardId_column_to_posts_table.js, server/routes/v1/boards.js, server/services/boards/getBoardBySlug.js, server/services/votes/getVotes.js
You can see posts for each board.
=> Each Board page

frontend/src/components/dashboard/Sidebar.vue, frontend/src/components/icons/Link.vue, frontend/src/components/post/CreatePost.vue, frontend/src/components/post/Post.vue, frontend/src/pages/dashboard/Overview.vue, frontend/src/pages/dashboard/board/DashboardBoard.vue, frontend/src/pages/dashboard/board/DashboardBoards.vue, frontend/src/pages/dashboard/board/DashboardCreateBoard.vue, frontend/src/pages/dashboard/post/DashboardPostView.vue, frontend/src/routes.js, frontend/src/styles/components/table.sass, frontend/src/styles/main.sass, frontend/src/styles/pages/dashboard/boards.sass
| Preview |
| --- |
| ![Screen Recording 2020-09-20 at 10 01 45 AM](https://user-images.githubusercontent.com/29014463/93694560-d50fc480-fb2a-11ea-9f25-983ea3881e61.gif) |
=> Dashboard Boards page

frontend/src/components/post/Post.vue, frontend/src/styles/components/post/post.sass, frontend/src/styles/pages/dashboard/overview.sass, server/controllers/post/filterPost.js, server/services/boards/getBoardById.js
| design preview |
| --- |
| ![logchimp post with board info](https://user-images.githubusercontent.com/29014463/93701954-ac8cc800-fb34-11ea-8612-f9240d7105c3.png) |
=> Add board info to post component

frontend/src/components/dashboard/Sidebar.vue, frontend/src/pages/dashboard/user/DashboardUsers.vue, frontend/src/routes.js, frontend/src/styles/main.sass, frontend/src/styles/pages/dashboard/users.sass, server/controllers/users/filter.js, server/controllers/users/index.js, server/routes/v1/users.js, server/services/users/getUsers.js
| Preview |
| --- |
| ![Screen Recording 2020-09-20 at 6 23 20 PM](https://user-images.githubusercontent.com/29014463/93711794-aa475f80-fb6e-11ea-8abd-d5ad720c2fb2.gif) |
=> Dashboard users

frontend/src/App.vue, frontend/src/components/Alert.vue, frontend/src/components/post/CreatePost.vue, frontend/src/components/post/Vote.vue, frontend/src/pages/Join.vue, frontend/src/pages/Login.vue, frontend/src/pages/dashboard/post/DashboardPostView.vue, frontend/src/pages/post/Edit.vue, frontend/src/pages/post/View.vue, frontend/src/pages/user/Settings.vue, frontend/src/store/modules/alerts.js
Update title with appropriate message and remove description.
Closes #89
=> Remove description from alerts vuex

server/controllers/auth/login.js, server/errorResponse.json, server/middlewares/token.js, server/routes/v1/boards.js, server/routes/v1/posts.js, server/routes/v1/votes.js
This PR includes the following changes:
* Validates the authorisation header
* Extract token from authorisation header
* Decode token to check if user exists and isn't blocked
* Validate JWT token
* Check for blocked users before login
This PR only resolves backend related issue #72.
=> Token middleware validate user

frontend/src/components/board/CreateBoard.vue, frontend/src/components/input/LText.vue, frontend/src/components/post/CreatePost.vue, frontend/src/components/post/Post.vue, frontend/src/pages/Join.vue, frontend/src/pages/Login.vue, frontend/src/pages/post/Edit.vue, frontend/src/pages/setup/Account.vue, frontend/src/pages/user/Settings.vue
Fix eslint vue "error" which were introduced in #127
=> Fix: eslint plugin vue v7 errors

frontend/src/components/dashboard/Sidebar.vue, frontend/src/components/icons/Info.vue, frontend/src/components/icons/Twitter.vue, frontend/src/styles/components/dashboard/sidebar.sass
| preview |
| --- |
| <img width="302" alt="Screenshot 2020-10-03 at 7 31 29 AM" src="https://user-images.githubusercontent.com/29014463/94980769-76930f00-054a-11eb-98de-4b07f617cfc4.png"> |
=> Add dropdown to Dashboard sidebar

frontend/src/components/Button.vue, frontend/src/components/board/CreateBoard.vue, frontend/src/components/post/CreatePost.vue, frontend/src/pages/Join.vue, frontend/src/pages/Login.vue, frontend/src/pages/dashboard/DashboardSettings.vue, frontend/src/pages/post/Edit.vue, frontend/src/pages/setup/Account.vue, frontend/src/pages/user/Settings.vue, frontend/src/styles/components/button.sass
Add opacity to button loading state and check for button loading early and add return statement.
```js
if (this.buttonLoading) {
return;
}
```
=> fix: button loading state

frontend/src/pages/dashboard/post/DashboardPostView.vue, frontend/src/pages/post/View.vue, frontend/src/styles/components/loader.sass
Show loader until the post loads.
=> Add loader to post view

.github/workflows/test.yml, .gitignore, package.json, scripts/create-config.sh, server/app.js, server/controllers/auth/login.js, server/controllers/auth/signup.js, server/database/config.js, server/jest.config.js, server/middlewares/token.js, server/utils/logchimpConfig.js, yarn.lock
Replace environment variable with `logchimp.config.json` for storing LogChimp site information.
**Example**
```json
{
"database": {
"host": "localhost",
"user": "lc",
"password": "password",
"name": "lc_db",
"port": 1002,
"ssl": false
},
"server": {
"port": 9090,
"secretKey": "Maposaketom3Xecysutoxah4Xyzuropivuxuve2"
}
}
```
=> Logchimp config file

.gitpod.Dockerfile, .gitpod.yml, README.md, frontend/vue.config.js, scripts/gitpod-init.sh
Add support for GitPod for contributors to get started with development environment.
=> Add GitPod support

frontend/src/App.vue, frontend/src/pages/dashboard/DashboardSettings.vue, frontend/src/store/modules/settings.js, package.json, server/controllers/settings/update.js, server/database/migrations/20201018201441_google-analytics-id-column-to-settings-table.js, yarn.lock
=> Integrate google analytics

frontend/src/components/post/Post.vue
Resolved eslint error with mutating props #135
=> fix: Resolve no-mutate-props (eslint error)

frontend/src/components/post/LatestPosts.vue, frontend/src/components/post/OldestPosts.vue, frontend/src/components/post/Post.vue, frontend/src/components/post/Vote.vue, frontend/src/modules/posts.js, frontend/src/pages/board/_url.vue, frontend/src/pages/dashboard/Index.vue, frontend/src/pages/dashboard/Posts.vue, frontend/src/pages/dashboard/post/_slug/Index.vue, frontend/src/pages/post/_slug/Index.vue, server/controllers/post/filterPost.js, server/routes/v1/posts.js, server/services/votes/getVotes.js
Refactor the getPosts API to make it work with any kind of filter.
* Boards
* Latest/oldest
=> Filter post with board ids

frontend/src/components/PowerBy.vue, frontend/src/layout/Dashboard.vue, frontend/src/layout/HeaderFooter.vue, frontend/src/styles/base.sass, frontend/src/styles/components/container.sass, frontend/src/styles/components/header.sass, frontend/src/styles/layout/dashboard.sass
=> Powered by LogChimp

frontend/src/components/ColorInput.vue, frontend/src/components/board/BoardForm.vue, frontend/src/components/input/LText.vue, frontend/src/components/input/Toggle.vue, frontend/src/components/input/ToggleItem.vue, frontend/src/modules/boards.js, frontend/src/pages/dashboard/Boards.vue, frontend/src/pages/dashboard/boards/Create.vue, frontend/src/pages/dashboard/boards/Settings.vue, frontend/src/routes.js, frontend/src/styles/components/breadcrumbs.sass, frontend/src/styles/components/colorInput.sass, frontend/src/styles/components/form.sass, frontend/src/styles/components/input.sass, frontend/src/styles/components/toggle.sass, frontend/src/styles/components/toggleItem.sass, frontend/src/styles/main.sass, frontend/tests/unit/colorInput.spec.js, frontend/tests/unit/toggle.spec.js, frontend/tests/unit/toggleItem.spec.js, server/controllers/boards/checkName.js, server/controllers/boards/create.js, server/controllers/boards/updateBoard.js
Creating a common `BoarForm` component; using it for creating and updating boards.
=> Edit board

frontend/src/components/dashboard/Sidebar.vue, frontend/src/pages/dashboard/settings/General.vue, frontend/src/routes.js, frontend/src/styles/components/dashboard/sidebar.sass
Add support for multiple sections in dashboard sidebar.
| Preview |
| --- |
| <img width="278" alt="CleanShot 2021-01-10 at 13 31 16@2x" src="https://user-images.githubusercontent.com/29014463/104117566-25b06500-5348-11eb-8186-71168840d802.png"> |
=> Refactor dashboard sidebar

frontend/src/components/icons/Eye.vue, frontend/src/components/icons/EyeOff.vue, frontend/src/modules/boards.js, frontend/src/pages/Boards.vue, frontend/src/pages/board/_url.vue, frontend/src/pages/dashboard/Boards.vue, frontend/src/pages/dashboard/boards/Settings.vue, server/controllers/boards/get.js, server/controllers/boards/index.js, server/controllers/boards/updateBoard.js, server/database/migrations/20200906184214_initial_boards_table.js, server/routes/v1/boards.js
Add the option to toggle board visibility on the site.
=> feat: Toggle boards visibility

.eslintignore, .eslintrc.js, .prettierrc.json, package.json
Play around with ESLint and Prettier configuration to set a fine-tune configuration for this project.
_Suggestions are welcome in the comment section below_
=> Refactor eslint prettier configuration

frontend/src/modules/roles.js, frontend/src/pages/dashboard/settings/roles/Index.vue, server/controllers/roles/get.js, server/controllers/roles/index.js, server/routes/v1/roles.js
Add GET "/api/v1/roles" APIs for showing roles in dashboard.
=> Get all roles (API + client)

frontend/src/components/dashboard/Sidebar.vue, frontend/src/components/icons/Grip.vue, frontend/src/modules/roadmaps.js, frontend/src/pages/dashboard/roadmaps/Index.vue, frontend/src/pages/dashboard/roadmaps/Settings.vue, frontend/src/routes.js, package.json, server/controllers/roadmaps/create.js, server/controllers/roadmaps/filter.js, server/controllers/roadmaps/index.js, server/controllers/roadmaps/roadmapByUrl.js, server/controllers/roadmaps/sort.js, server/controllers/roadmaps/updateRoadmap.js, server/database/migrations/20201224104136_add-roadmaps-table.js, server/middlewares/roadmapExists.js, server/routes/v1/roadmaps.js, yarn.lock
Add roadmap to dashboard along with `CREATE`, `UPDATE`, `DELETE`, `SORT` APIs.
=> feat: Roadmap

frontend/src/components/Header.vue, frontend/src/components/board/BoardSuggestion.vue, frontend/src/components/dashboard/Sidebar.vue, frontend/src/components/dropdown/Dropdown.vue, frontend/src/components/dropdown/DropdownItem.vue, frontend/src/components/dropdown/DropdownWrapper.vue, frontend/src/components/post/Post.vue, frontend/src/modules/boards.js, frontend/src/modules/posts.js, frontend/src/modules/roadmaps.js, frontend/src/pages/dashboard/post/_slug/Index.vue, frontend/src/pages/post/_slug/Index.vue, frontend/src/routes.js, frontend/src/store/modules/user.js, frontend/src/styles/components/board/boardSuggestion.sass, frontend/src/styles/components/dropdown.sass, frontend/src/styles/components/post/post.sass, frontend/src/styles/main.sass, frontend/tests/unit/BoardSuggestion.spec.js, package.json, server/controllers/boards/index.js, server/controllers/boards/searchBoard.js, server/controllers/post/filterPost.js, server/controllers/post/postBySlug.js, server/controllers/post/updatePost.js, server/controllers/roadmaps/index.js, server/controllers/roadmaps/searchRoadmap.js, server/routes/v1/boards.js, server/routes/v1/roadmaps.js, yarn.lock
| **Preview** |
| --- |
| <img width="1021" alt="CleanShot 2021-01-27 at 17 49 12@2x" src="https://user-images.githubusercontent.com/29014463/105990127-12cbbd80-60c8-11eb-82cd-1080587cb66e.png"> |
=> Dashboard post settings

frontend/src/modules/boards.js, frontend/src/pages/dashboard/boards/Index.vue
| Preview |
| --- |
| <img width="1255" alt="CleanShot 2021-02-04 at 11 11 24@2x" src="https://user-images.githubusercontent.com/29014463/106850020-bf65fa80-66d9-11eb-8466-38dc6478b2ab.png"> |
=> Add delete board option to dashboard

index.js, package.json, server/app.js
Split the express app and running nodejs server as it will be later used for writing tests for APIs and more.
=> split express app & run nodejs server

tests/api/v1/auth/login.spec.js
tests for `login.spec.js` are [passing](https://github.com/logchimp/logchimp/actions/runs/545311974).
=> add login API tests

server/controllers/roadmaps/deleteById.js, server/controllers/roadmaps/index.js, server/controllers/roadmaps/roadmapByUrl.js, server/routes/v1/roadmaps.js
Add APIs for deleting roadmap by ID.
=> delete roadmap by Id

server/controllers/auth/signup.js, server/database/migrations/20201004110523_create-settings-table.js
A feature where the site owner can toggle the settings for allowing their customers to sign up or not.
=> feature check for allowedSignup

tests/api/v1/auth/setup.spec.js, tests/api/v1/auth/signup.spec.js
This PR is created from https://github.com/logchimp/logchimp/pull/457
=> tests: signup & setup

server/database/migrations/20210731141417_add-developer_mode-to-settings.js, tests/integration/v1/settings.test.js
By enabling `developer_mode` the user will see few more things on site which may or may not look **magical**.
=> feat: developer mode

.profile, .railway/create-config
This PR add a configuration file allowing easy deployment to railway.
=> feat: add railway deploy button

server/controllers/users/getUserInfo.js, server/controllers/users/index.js, server/controllers/users/updateUserInfo.js, server/database/migrations/20210808173003_add-notes-to-users-table.js, server/routes/v1/users.js
`RUD` means read, update and delete. This PR doesn't add the option to create new user from dashboard.
=> feat: RUD user from dashboard

.github/workflows/test.yml, packages/theme/package.json, yarn.lock
Use `sass-loader@10.2.0` version.
=> fix: test theme build in CI pipeline

packages/server/services/auth/createUser.js, tests/integration/v1/auth/signup.spec.js
Closes https://github.com/logchimp/logchimp/issues/532
=> fix: case insensitive email signup

.gitpod.yml, scripts/gitpod-init.sh
Installing code dependencies at `init` step of gitpod.
=> chore(fix:gitpod): setup command

packages/theme/src/App.vue, packages/theme/src/pages/EmailVerify.vue, packages/theme/src/pages/Index.vue, packages/theme/src/pages/Join.vue, packages/theme/src/pages/Login.vue, packages/theme/src/pages/Roadmaps.vue, packages/theme/src/pages/Settings.vue, packages/theme/src/pages/boards/Index.vue, packages/theme/src/pages/boards/_url.vue, packages/theme/src/pages/dashboard/boards/Settings.vue, packages/theme/src/pages/dashboard/posts/_slug/Index.vue, packages/theme/src/pages/dashboard/roadmaps/Settings.vue, packages/theme/src/pages/dashboard/settings/billing.vue, packages/theme/src/pages/dashboard/settings/roles/Settings.vue, packages/theme/src/pages/passwordReset/Confirm.vue, packages/theme/src/pages/passwordReset/Index.vue, packages/theme/src/pages/posts/_slug/Edit.vue, packages/theme/src/pages/posts/_slug/Index.vue, packages/theme/src/pages/setup/CreateAccount.vue, packages/theme/src/pages/setup/CreateBoard.vue, packages/theme/src/pages/setup/Welcome.vue
Ref: https://unhead.harlanzw.com/integrations/vue/reactivity
=> fix(theme): Head tag reactivity with computed getters

.devcontainer/devcontainer.json, .github/workflows/test.yml, .gitpod.yml, biome.json, package.json, packages/theme/src/modules/roles.ts, packages/theme/src/modules/site.ts, packages/theme/src/pages/Settings.vue, packages/theme/src/store/alert.ts, packages/theme/src/store/settings.ts, packages/theme/src/store/user.ts, packages/theme/src/utils/tokenError.ts, packages/theme/src/vite-env.d.ts
A follow-up PR from https://github.com/logchimp/logchimp/pull/851
Closes https://github.com/logchimp/logchimp/pull/841
=> feat: rome to biome

packages/server/controllers/auth/isSiteSetup.js, packages/server/tests/integration/v1/auth/setup.spec.js, packages/server/tests/utils/db.js
This PR fixes the issue of `isSiteSetup` API return all the owner user data _(including sensitive data)_.
=> fix: isSiteSetup return boolean value

packages/theme/src/ee/components/roadmap/RoadmapColumn.vue, packages/theme/src/pages/Roadmaps.vue
| Preview |
| --- |
| <img width="2490" height="1584" alt="CleanShot 2025-07-28 at 19 58 28@2x" src="https://github.com/user-attachments/assets/a7b06ddd-ae1e-4145-8f5b-484be9a7dfe6" /> |
=> feat(theme/Roadmaps): set min-height to roadmap columns

packages/server/tests/integration/v1/users/updateProfile.spec.js
Provide integration test for the api  `/v1/users/profile`  which is the updateProfile controller
Fixes #813
=> test: Wrote integration test updating user name (with length check)

.github/workflows/test.yml, packages/server/package.json, packages/server/src/database/config.ts
The goal of this PR to move forward with ES Module file for knex config file.
=> fix(server): remove module.exports in db config

docker-compose.dev.yml, docker/local/server.Dockerfile, packages/server/docker-dev-entrypoint.sh
Fixes docker compose dev build for contribution. ~Bumped up the postgres image from `12` to `12.4`~
=> fix: docker compose

packages/server/tests/integration/v1/users/getProfile.spec.ts
Fixes #1095
Wrote integration tests for [GET] /users/profile
**Changes made**
- `packages/server/tests/integration/v1/users/getProfile.spec.ts`
=> Test integration for getting user profile

packages/server/src/ee/middleware/roleExists.ts
Fixes #1132
**Changes made**
- `packages/server/src/ee/middleware/roleExists.ts`
=> fix: server crashes for `/api/v1/roles/undefined` API endpoint

packages/theme/src/components/ui/Alert/Alert.vue, packages/theme/src/ee/pages/dashboard/settings/roles/Settings.vue
Introduces alert when role:assign option is toggled in settings page while creating a role.
Fixes #1108
=> feat: show alert in roles page when creating role with role:assign permission

.github/workflows/test.yml, packages/server/src/routes/v1/auth.ts, packages/server/tests/integration/v1/auth/email.spec.ts
Closes https://github.com/logchimp/logchimp/issues/988
=> feat: add integration test for `[POST] /auth/email/verify`

.github/workflows/codeql-analysis.yml
> Under testing
**Changes made**
- Bump up version of CodeQL tests
=> update codeql test

.github/workflows/codeql-analysis.yml
Supposed to fix the codeql test to run in master without issues.
=> fix: codeql test

packages/server/tests/integration/v1/roles.spec.ts
**Changes made**
- `packages/server/tests/integration/v1/roles.spec.ts`
- adds test case to get role by ID with permissions
=> Add extra test for `GET /roles/:id`

packages/server/tests/integration/v1/posts.spec.ts, packages/server/tests/integration/v1/settings.test.ts, packages/server/tests/utils/seed/settings.ts
Tests for creating comments.
No permissions required.
=> Test(api): Create Comment. [POST] /posts/:post_id/comments

packages/theme/src/pages/Index.vue
Aside column grows with growing posts column
Assigned full height to the column.
Applied sticky feature to aside column to make it visible even during scroll
https://github.com/user-attachments/assets/0d099534-5afd-49ba-9c86-dde4dd88025b
=> Fix aside column stretch and introduced sticky feature to aside column

packages/theme/src/components/ui/Dialog.vue, packages/theme/src/ee/components/dashboard/users/TabularItem/TabularItem.vue, packages/theme/src/ee/components/dashboard/users/TabularItem/UserInfoDialog.vue
Added Dialog.vue component for reusable dialogs.
Added UserInfoDialog.vue to display detailed user info.
Couldn't display user's joining date (user.createdAt) in the User Info Dialog.
=> feat: added user info dialog 

.github/workflows/biome-tools.yml, .github/workflows/test.yml
=> refactor: Moved biome steps in test.yml as separate workflow file
